services:
  bring-up:
    image: alpine:latest
    command: ["sh", "-c", "echo 'Application is up and running!'"]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      # dont require a password for local development
      POSTGRES_HOST_AUTH_METHOD: trust
      # run init sql script on startup
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user"]
      interval: 60s
      timeout: 5s
      retries: 5

